extends:
- stylelint-config-standard

ignoreFiles:
- '**/*.ico'
- '**/*.png'
- '**/*.json'

rules:
  indentation: 2
  max-line-length: 120
  string-quotes: single
  no-duplicate-selectors: true
  color-hex-case: lower
  font-family-name-quotes: always-unless-keyword
  # stylelint-config-standard mandates lowercase kebab-case, but we want to follow React component names,
  # so we allow things like 'NavigationBar-inner'
  selector-class-pattern: ['^([A-Za-z][a-z0-9]*)+(-[a-z0-9]+)*$', {
    message: 'Expected class selector to be KeBab-case'
  }]
  custom-property-pattern: ['^([A-Za-z][a-z0-9]*)+(-[a-z0-9]+)*$', {
    message: 'Expected custom property name to be KeBab-case'
  }]
