# FOR DEVELOPMENT ONLY (building from source)
# Use the compose file specified in README.md for regular deployments.

version: '3.1'

networks:
  internal:

volumes:
  mongodb_data:
  mongodb_config:

services:

  mongodb:
    image: mongo:6
    container_name: wg_mongodb
    networks:
      - internal
    volumes:
      - 'mongodb_data:/data/db'
      - 'mongodb_config:/data/configdb'

  wg_system:
    build: .
    image: wg-system
    container_name: wg_system
    depends_on:
      - mongodb
    networks:
      - internal
    ports:
      - '8080:8080'
    environment:
      MONGODB_URI: 'mongodb://wg_mongodb/wgsystem'
